### ISSUE TITLE
Retained audio is cut short when using listen_key

### ISSUE THREAD

**Issue by jwebmeister** [jwebmeister/dragonfly#3]
### Problem Description
The retained audio when using `listen_key` is very often cut short, in the order of 50-100ms of the end of the utterance is missing from the retained audio.  

This issue may or may not be affecting speech recognition accuracy, however the majority of the commands with retained audio that were cut short were still recognised correctly.
This issue does however significantly affect the use of retained audio + metadata for the purpose of training speech models.

### Possible causes
It is possible that either: 
1. the internals (or settings) of the engine is cutting the audio short, e.g. too coarse an audio `block` size, discarding the last audio `block`; or
2. the user is releasing the `listen_key` too early.

### Potential solutions
Item (1) should be investigated first to identify and address any bugs or issues with the engine, that might also be causing other issues.

Item (2) could be addressed by changing how utterances (i.e. phrases) are ended, specifically to add a configurable time delay between `listen_key` release and ending the utterance `end_of_phrase()`.

### Tasks

- [x] Investigate audio being cut short due to engine internals and/or settings.
- [x] Fix any bugs or issues with engine internals and/or settings causing retained audio to be cut short.
- [x] Determine if a "configurable time delay between `listen_key` release and ending the utterance `end_of_phrase()`" is required.
- [x] If required, develop "configurable time delay between `listen_key` release and ending the utterance `end_of_phrase()`"
- [x] Testing and tuning in Tacspeak
