### ISSUE TITLE
Tech debt and Linux X11, macOS support

### ISSUE THREAD

**Issue by jwebmeister** [jwebmeister/dragonfly#4]
### Problem description

All of the features implemented within this forked modified version of Dragonfly have tech debt. 
Most significantly they have been implemented to only work on:

1. OS = Windows 10/11 x64
2. Backend speech engine = Kaldi

While it is likely some new features can't (practically) be ported to other backend speech engines, it should be possible to refactor all (or most) functionality to work across the other Dragonfly supported OSs (Linux X11, macOS and Windows).

Beyond being able to support more OSs, it would be best to address the current tech debt to make future syncs with the upstream repo [dictation-toolbox/dragonfly](https://github.com/dictation-toolbox/dragonfly) easier, and ideally be able to contribute back to the project.

### Tasks

- [ ] Review `notify_partial_recognition` and `KaldiRecObsManager` - is it complete and consistent? can it be refactored/ported to other speech engines? can and/or should it be refactored to use `grammar` as opposed to `recobs`?
- [ ] Refactor [dragonfly/actions/getkeystate.py](https://github.com/jwebmeister/dragonfly/blob/master/dragonfly/actions/getkeystate.py) to support all OSs, and make necessary changes in [dragonfly/engines/backend_kaldi/engine.py](https://github.com/jwebmeister/dragonfly/blob/master/dragonfly/engines/backend_kaldi/engine.py)
- [ ] Review `listen_key` and `listen_key_toggle` - can it be refactored/ported to other speech engines?
- [ ] Add documentation
